---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wocky-config
  namespace: wocky-testing
  labels:
    app: wocky
    env: testing
data:
  WOCKY_ENV: prod
  WOCKY_INST: testing
  WOCKY_HOST: testing.dev.tinyrobot.com
  WOCKY_IQ_CRASH_RESPONSE: error_with_dump
  WOCKY_TROS_S3_BUCKET: wocky-kube-tros-testing
  WOCKY_PUSH_ENABLED: "false"
  WOCKY_INDEXING_SYSTEM: test
  WOCKY_USER_INDEX_NAME: ""
  WOCKY_BOT_INDEX_NAME: ""
  WOCKY_ENABLE_BYPASS: "true"
  WOCKY_DB_HOST: wocky-testing.cx7fev3pluk8.us-west-2.rds.amazonaws.com
  WOCKY_DB_NAME: wocky_testing
  WOCKY_DB_WATCHER_QUEUE: wocky-testing-db-watcher.fifo
  WOCKY_ENTER_DEBOUNCE_SECONDS: "0"
  WOCKY_EXIT_DEBOUNCE_SECONDS: "0"
  AWS_ACCESS_KEY_ID: AKIAISCBKX42EUVSVXAQ
  HONEYBADGER_ENV: testing
  REPLACE_OS_VARS: "true"
  REDIS_HOST: wocky-cache.byxmud.ng.0001.usw2.cache.amazonaws.com
  REDIS_DB: "3"
  DAWDLE_QUEUES: "wocky-dawdle-testing"
